Repository LukeHuckman/RedBot, pull requests merged in 2020-11, with the labels that each got.

#18 Bug Report Template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#19 DuckDuckGo search
  README.md
  src/main/java/RedBot/Bot.java
Labels: enhancement

#26 Replaced DuckDuckGo for Google
  README.md
  src/main/java/RedBot/Bot.java
  src/main/java/RedBot/HParser.java
Labels: bug, enhancement
